[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
CN = vram-webhook.devops-system.svc

[v3_req]
keyUsage = keyEncipherment, dataEncipherment, digitalSignature
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = vram-webhook
DNS.2 = vram-webhook.devops-system
DNS.3 = vram-webhook.devops-system.svc
DNS.4 = vram-webhook.devops-system.svc.cluster.local
